### PR TITLE
add Login page layout

### LINKED ISSUE #4: Create Login page layout
Create the layout for Login Page as we discussed earlier.
> Effected file: `/src/pages/authentication/Login.tsx`.
> Preview url: `/login`

**Only update the markup. No need to implement the logic.**

### PR DESCRIPTION
**Pull request by thatsuman**
This PR closes #4 

**Preview:**

- desktop mode:
  
image

- mobile:

WhatsApp Image 2022-04-28 at 11 34 49 AM

### CODE REVIEW

**Comment by asimbera** [comment]
- Please add `Forgot password?` link between the password field and sign in button.
- Replace anchor tags with `Link` component from `react-router-dom` library.

**Comment by thatsuman** [comment]
> Please add `Forgot password?` link between the password field and sign in button.

Why? then as per our policies if a user forgot his/her password he/she must make a payment before opt for `Forgot Password?`

**Comment by asimbera** [comment]
> Why? then as per our policies if a user forgot his/her password he/she must make a payment before opt for `Forgot Password?` 


Great business idea .

Ab to paisa hi paisa hoga.

**Comment by asimbera** [comment]
Kindly rebase on main and run the formatter.

**Comment by asimbera** [comment]
Closing.

**Pull request closed without merging**
