### PR TITLE
add verify email page layout

### LINKED ISSUE #20: Create verify email page layout
Create the layout for Verify Email Page as we discussed earlier.
> Effected file: `/src/pages/authentication/Verify.tsx`.
> Preview url: `/verify-email`

**Only update the markup. No need to implement the logic.**

### PR DESCRIPTION
**Pull request by thatsuman**
Fixes #20 

I didn't add the alert notification functionality, just made the layout.

### CODE REVIEW

**Comment by thatsuman** [comment]
Seems I messed up with branches. Previous commits are also shown here.

**Comment by asimbera** [comment]
You needed to switch to dev and pull there. And diverge from there to a branch with non conflicting name.

**Comment by thatsuman** [comment]
> You needed to switch to dev and pull there. And diverge from there to a branch with non conflicting name.

Ok then I'll make a fresh PR. And anything to change in code?

**Comment by thatsuman** [comment]
Closing

**Pull request closed without merging**
